common: &common
  name:
    item: "画面名"
    sub-item: "項目1"
    sub-sub-item: "項目2"
    sub-sub-sub-item: "条件1"
    sub-sub-sub-sub-item: "条件2"
    number: "No."
    steps: "手順"
    expected: "期待値"
    notes: "備考"

md:
  mark:
    item: "## "
    sub-item: "### "
    sub-sub-item: "#### "
    sub-sub-sub-item: "##### "
    sub-sub-sub-sub-item: "###### "
    steps: "[0-9]+. "
    expected: "* [ ] "
    notes: "- "
  <<: *common


excel:

  font: "Meiryo UI"

  # どこまでマルチインデックス化（マージ）するか
  index:
    item: true
    sub-item: true
    sub-sub-item: true
    sub-sub-sub-item: true
    sub-sub-sub-sub-item: true

  # エクセルでの列幅
  length:
    item: 20
    sub-item: 20
    sub-sub-item: 20
    sub-sub-sub-item: 20
    sub-sub-sub-sub-item: 20
    number: 6
    steps: 25
    expected: 25
    notes: 40

  # 各列の水平方向位置
  horizontal:
    item: "center"
    sub-item: "center"
    sub-sub-item: "left"
    sub-sub-sub-item: "left"
    sub-sub-sub-sub-item: "left"
    number: "center"
    steps: "left"
    expected: "left"
    notes: "left"

  # 各列の垂直方向位置
  vertical:
    item: "top"
    sub-item: "top"
    sub-sub-item: "top"
    sub-sub-sub-item: "top"
    sub-sub-sub-sub-item: "top"
    number: "center"
    steps: "top"
    expected: "top"
    notes: "top"
  <<: *common
